// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    ReportIcon: typeof import('src/components/ReportIcon.vue')['default']
    SettingIcon: typeof import('src/components/SettingIcon.vue')['default']
    SimulationIcon: typeof import('src/components/SimulationIcon.vue')['default']
    StockIcon: typeof import('src/components/StockIcon.vue')['default']
    SystemIcon: typeof import('src/components/SystemIcon.vue')['default']
    UserPopover: typeof import('src/components/UserPopover/UserPopover.vue')['default']
    IconFont: typeof import('src/components/IconFont/IconFont')['default']
  }
}

export {}
