// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    ChangePassword: typeof import('./components/ChangePassword/ChangePassword.vue')['default']
    ReportIcon: typeof import('./components/ReportIcon.vue')['default']
    SettingIcon: typeof import('./components/SettingIcon.vue')['default']
    SimulationIcon: typeof import('./components/SimulationIcon.vue')['default']
    SjModal: typeof import('./components/SjModal/SjModal.vue')['default']
    StockIcon: typeof import('./components/StockIcon.vue')['default']
    SystemIcon: typeof import('./components/SystemIcon.vue')['default']
    UserPopover: typeof import('./components/UserPopover/UserPopover.vue')['default']
  }
}

export { }
